### PR TITLE
fix unvisible bottom button

### PR DESCRIPTION
**Pull request by suhaotian**
**before:** 
75f519ca-6f6a-4216-8c7a-9d4390f63c32

**now:**
image

### CODE REVIEW

**Comment by zalmoxisus** [comment]
Thanks a lot! Does it work also when the widow's width is smaller (when the labels are hidden)?

**Comment by zalmoxisus** [comment]
Unfortunately, I cannot reproduce that issue neither in Chrome (last version) nor in Safari. But this fix makes the margin height unproportional:
screen shot 2016-06-16 at 5 18 01 pm

Wouldn't just removing `maxHeight` [here](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/styles.js#L44) solve that issue?

**Comment by suhaotian** [comment]
@zalmoxisus  Remove **maxHeight** didn't work : (

**Comment by suhaotian** [comment]
@zalmoxisus Yes, It work~~

image

**Comment by suhaotian** [comment]
You can open the window,  then inspect it, and to chane css.

**Comment by zalmoxisus** [comment]
@suhaotian, that's great! 

What if instead of `margin: '0 0.3em',` we use `margin: 'auto 0.3em',`? Would that work?

What we want to accomplish here, is to hide the label when it doesn't fit the button (when the window's height is too small). That's why we keep `buttonBar` fixed and it caused that issue.

**Comment by zalmoxisus** [comment]
If yes. Could you update the pr so it will keep the buttons aligned vertically when the height is smaller.

Instead of 
screen shot 2016-06-16 at 5 43 08 pm
It will be
screen shot 2016-06-16 at 5 43 21 pm

**Comment by suhaotian** [comment]
@zalmoxisus 👌 

c15af752-c40d-4fbe-b047-24d3889ef348

**Comment by zalmoxisus** [comment]
Thanks a lot! Merged here, and also published the extension, should appear `v2.0.2` on Chrome store in about an hour.

**Comment by suhaotian** [comment]
It's my pleasure :smile_cat:

**Pull request merged**
