### PR TITLE
Destructure prop types

### PR DESCRIPTION
**Pull request by tyleriguchi**

### CODE REVIEW

**Comment by zalmoxisus** [comment]
Thanks for working in that, but I already removed the button component in #30 in favour of [`devui`'s Button](https://github.com/zalmoxisus/devui/blob/master/src/Button/Button.js).

**Comment by tyleriguchi** [comment]
Yeah after I opened this I noticed you had a lot of work on that other branch. To be honest this pull request was me getting distracted, originally was looking into being able to configure to the light theme. 

I'll close this guy out.

**Comment by zalmoxisus** [comment]
It's available as `remotedev-app@alpha` and the light theme is by default there.

**Comment by tyleriguchi** [comment]
Oh awesome, I'll have to try it out, thanks!

**Pull request closed without merging**
